name: SimpPay
version: '$version'
main: org.simpmc.simppay.SPPlugin
api-version: '1.21'
author: 'typical.smc'
libraries:
  - com.h2database:h2:2.3.232
  - com.zaxxer:HikariCP:5.0.1
  - com.j256.ormlite:ormlite-jdbc:6.1
  - commons-codec:commons-codec:1.18.0
#  - redis.clients:jedis:4.3.1

permission:
  simppay.napthe:
    default: true
    description: Allow player to use /simppay command
  simppay.banking:
    default: op
  simppay.napthenhanh:
    default: true
    description: Allow player to use /napthenhanh command